# Site settings
name: 青春梦想
email: xgl_scu@163,com
author: xiong xiong
url: http://www.baidu.com
resume_site: http://www.baidu.com/
github: https://github.com/longfirefly/
baseurl: ""
description: 该奋斗的年纪不能选择安逸!
meta_description: 小熊熊;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 该学学，该玩玩
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 0

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: longfirefly

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

